{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "1. What is the role of try and exception block?\n",
    "Answer:\n",
    "try:\n",
    "  # Code that might cause an error to be present in try block\n",
    "except Exception as e:\n",
    "  # Code to be executed if an error occurs to be present in except block\n",
    "\n",
    "Eg:\n",
    "try:\n",
    "  x = int(input(\"Enter a number: \"))\n",
    "except ValueError:\n",
    "  print(\"That was not a valid number.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "2. What is the syntax for a basic try-except block?\n",
    "Answer:\n",
    "try:\n",
    "  # Code that might cause an error to be present in try block\n",
    "except Exception as e:\n",
    "  # Code to be executed if an error occurs to be present in except block\n",
    "\n",
    "Eg:\n",
    "try:\n",
    "  x = int(input(\"Enter a number: \"))\n",
    "except ValueError:\n",
    "  print(\"That was not a valid number.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "3. What happens if an exception occurs inside a try block and there is no matching\n",
    "except block?\n",
    "Answer:\n",
    "If an exception occurs inside a try block and there is no matching except block,\n",
    "the exception will be unhandled. This means that the program will crash and the user will see an error message."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "4. What is the difference between using a bare except block and specifying a specific\n",
    "exception type?\n",
    "Answer:\n",
    "The main difference between using a bare except block and specifying a specific exception type is that a bare except block will catch all exceptions,\n",
    "while specifying a specific exception type will only catch that specific exception.\n",
    "\n",
    "A bare except block is equivalent to using the Exception keyword in the except clause.\n",
    "This means that the except block will be executed if any exception occurs in the try block, regardless of the type of exception.\n",
    "\n",
    "Specifying a specific exception type in the except clause will only catch that specific exception.\n",
    "For example, the following code will only catch the ValueError exception:\n",
    "try:\n",
    "  x = int(\"abc\")\n",
    "except ValueError:\n",
    "  print(\"That was not a valid number.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "5. Can you have nested try-except blocks in Python? If yes, then give an example.\n",
    "Answer: Yes, we can have nested try-except blocks in Python.  Can have try block inside another try block.\n",
    "try:\n",
    "  try:\n",
    "    x = int(input(\"Enter a number: \"))\n",
    "  except ValueError:\n",
    "    print(\"That was not a valid number.\")\n",
    "  else:\n",
    "    try:\n",
    "      y = x / 0\n",
    "    except ZeroDivisionError:\n",
    "      print(\"Division by zero error.\")\n",
    "    else:\n",
    "      print(\"x / y = \", x / y)\n",
    "except Exception as e:\n",
    "  print(\"An error occurred:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "6. Can we use multiple exception blocks, if yes then give an example.\n",
    "Answer:Yes, we can use multiple exception blocks in Python. Can have multiple except blocks following a single try block.\n",
    "try:\n",
    "  x = int(input(\"Enter a number: \"))\n",
    "except ValueError:\n",
    "  print(\"That was not a valid number.\")\n",
    "except ZeroDivisionError:\n",
    "  print(\"Division by zero error.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "7. Write the reason due to which following errors are raised:\n",
    "a. EOFError\n",
    "b. FloatingPointError\n",
    "c. IndexError\n",
    "d. MemoryError\n",
    "e. OverflowError\n",
    "f. TabError\n",
    "g. ValueError\n",
    "\n",
    "Answer:\n",
    "EOFError: This error is raised when the end of a file is reached unexpectedly.\n",
    "This can happen if the user presses Ctrl+D or Ctrl+Z while entering input from the console, or if the file is empty.\n",
    "\n",
    "FloatingPointError: This error is raised when a floating point operation fails.\n",
    "This can happen if the operation results in a number that is too large or too small to be represented by a floating point number, or if the operation is mathematically undefined.\n",
    "\n",
    "IndexError: This error is raised when an index is out of range for a sequence.\n",
    "This can happen if you try to access an element of a list or string that does not exist, or if you try to slice a sequence with a start or end index that is out of range.\n",
    "\n",
    "MemoryError: This error is raised when the Python interpreter runs out of memory.\n",
    "This can happen if your program is trying to allocate too much memory, or if your program is leaking memory.\n",
    "\n",
    "OverflowError: This error is raised when a numeric operation results in a value that is too large to be represented by the data type.\n",
    "This can happen if you try to divide a number by zero, or if you try to raise a number to a power that is too large.\n",
    "\n",
    "TabError: This error is raised when a tab character is encountered in a string literal that is not being used as a literal tab character.\n",
    "This can happen if you forget to escape the tab character with a backslash.\n",
    "\n",
    "ValueError: This error is raised when a function or operator is passed a value that is not of the correct type or that does not meet the expected conditions.\n",
    "This can happen if you try to convert a string to an integer, or if you try to divide a number by zero.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "8. Write code for the following given scenario and add try-exception block to it.\n",
    "a. Program to divide two numbers\n",
    "b. Program to convert a string to an integer\n",
    "c. Program to access an element in a list\n",
    "d. Program to handle a specific exception\n",
    "e. Program to handle any exception\n",
    "Answer:\n",
    "#a. Program to divide two numbers\n",
    "try:\n",
    "  a = int(input(\"Enter the first number: \"))\n",
    "  b = int(input(\"Enter the second number: \"))\n",
    "  print(a / b)\n",
    "except ValueError:\n",
    "  print(\"That was not a valid number.\")\n",
    "except ZeroDivisionError:\n",
    "  print(\"Division by zero error.\")\n",
    "#b. Program to convert a string to an integer\n",
    "try:\n",
    "  number_str = input(\"Enter a number: \")\n",
    "  number = int(number_str)\n",
    "  print(number)\n",
    "except ValueError:\n",
    "  print(\"That was not a valid number.\")\n",
    "\n",
    "#c. Program to access an element in a list\n",
    "list_nums = [1, 2, 3, 4, 5]\n",
    "\n",
    "try:\n",
    "  index = int(input(\"Enter the index of the element you want to access: \"))\n",
    "  print(list_nums[index])\n",
    "except IndexError:\n",
    "  print(\"The index is out of range.\")\n",
    "\n",
    "#d. Program to handle a specific exception\n",
    "try:\n",
    "  a = int(input(\"Enter the first number: \"))\n",
    "  b = int(input(\"Enter the second number: \"))\n",
    "  print(a / b)\n",
    "except ZeroDivisionError:\n",
    "  print(\"Division by zero error.\")\n",
    "\n",
    "#e. Program to handle any exception\n",
    "try:\n",
    "  a = int(input(\"Enter the first number: \"))\n",
    "  b = int(input(\"Enter the second number: \"))\n",
    "  print(a / b)\n",
    "except Exception as e:\n",
    "  print(e)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
